export interface LayerRegistryEntry {
  id: string;
  displayName: string;
  category: 'boundary' | 'raster' | 'geology' | 'infrastructure' | 'hazard' | 'rainfall';
  availability: 'Available' | 'Scenario / Proxy Mode';
  processingPhase: 'Phase 2' | 'Phase 4' | 'Phase 5' | 'Phase 6';
  source: string;
  units: string;
  tileOrSourceUrl: string;
  defaultVisibility: boolean;
  opacity: number;
  legend: {
    type: 'fill' | 'line' | 'circle' | 'gradient';
    color: string;
    colors?: string[];
    labels?: string[];
  };
  description: string;
  errorMessage: string;
  dataVersion: string;
}

export const MASTER_LAYER_REGISTRY: LayerRegistryEntry[] = [
  {
    id: "jk_boundary",
    displayName: "J&K UT Outer Boundary",
    category: "boundary",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "Survey of India / Official Boundary Dataset",
    units: "Polygon",
    tileOrSourceUrl: "/api/v1/districts/boundary",
    defaultVisibility: true,
    opacity: 0.8,
    legend: {
      type: "line",
      color: "#38bdf8"
    },
    description: "Verified outer boundary polygon of Jammu & Kashmir Union Territory.",
    errorMessage: "Unable to load J&K boundary geometry.",
    dataVersion: "v1.0.0"
  },
  {
    id: "district_boundaries",
    displayName: "20-District Boundaries",
    category: "boundary",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "20 J&K UT District Geometries",
    units: "20 Districts",
    tileOrSourceUrl: "/api/v1/districts/boundary",
    defaultVisibility: true,
    opacity: 0.6,
    legend: {
      type: "line",
      color: "#0ea5e9"
    },
    description: "20 official district boundary polygons (Mirpur & Muzaffarabad excluded).",
    errorMessage: "Unable to load district boundaries.",
    dataVersion: "v1.0.0"
  },
  {
    id: "susceptibility_prob",
    displayName: "Static Susceptibility Probability",
    category: "hazard",
    availability: "Available",
    processingPhase: "Phase 4",
    source: "XGBoost 30-Predictor ML Model",
    units: "Probability (0.0 - 1.0)",
    tileOrSourceUrl: "/api/v1/tiles/susceptibility_prob/{z}/{x}/{y}.png",
    defaultVisibility: true,
    opacity: 0.75,
    legend: {
      type: "gradient",
      color: "#f59e0b",
      colors: ["#22c55e", "#84cc16", "#eab308", "#f97316", "#ef4444"],
      labels: ["Very Low (<0.2)", "Low (0.2-0.4)", "Moderate (0.4-0.6)", "High (0.6-0.8)", "Very High (>=0.8)"]
    },
    description: "Statewide 100m static landslide susceptibility probability generated by XGBoost ML model.",
    errorMessage: "Susceptibility probability layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "susceptibility_class",
    displayName: "Static Susceptibility Class",
    category: "hazard",
    availability: "Available",
    processingPhase: "Phase 4",
    source: "GeoSlide-JK 5-Class Rating Matrix",
    units: "Classes (1-5)",
    tileOrSourceUrl: "/api/v1/tiles/susceptibility_class/{z}/{x}/{y}.png",
    defaultVisibility: false,
    opacity: 0.75,
    legend: {
      type: "gradient",
      color: "#ef4444",
      colors: ["#22c55e", "#84cc16", "#eab308", "#f97316", "#ef4444"],
      labels: ["1: Very Low", "2: Low", "3: Moderate", "4: High", "5: Very High"]
    },
    description: "5-class static susceptibility rating raster mapped across J&K UT.",
    errorMessage: "Susceptibility class layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "dynamic_hazard_index",
    displayName: "Dynamic Hazard Index",
    category: "rainfall",
    availability: "Scenario / Proxy Mode",
    processingPhase: "Phase 5",
    source: "H_dyn = S * (Rain_24h / P90)",
    units: "Index Score",
    tileOrSourceUrl: "/api/v1/tiles/dynamic_hazard_index/{z}/{x}/{y}.png",
    defaultVisibility: false,
    opacity: 0.75,
    legend: {
      type: "gradient",
      color: "#dc2626",
      colors: ["#0f172a", "#22c55e", "#84cc16", "#eab308", "#f97316", "#ef4444"],
      labels: ["0.0", "0.15", "0.35", "0.60", "0.90+"]
    },
    description: "Dynamic landslide hazard index computed from static susceptibility & 24h rainfall proxy ratio.",
    errorMessage: "Dynamic hazard index layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "dynamic_hazard_class",
    displayName: "Dynamic Hazard Class",
    category: "rainfall",
    availability: "Scenario / Proxy Mode",
    processingPhase: "Phase 5",
    source: "5-Class Dynamic Rating Matrix",
    units: "Classes (1-5)",
    tileOrSourceUrl: "/api/v1/tiles/dynamic_hazard_class/{z}/{x}/{y}.png",
    defaultVisibility: false,
    opacity: 0.75,
    legend: {
      type: "gradient",
      color: "#b91c1c",
      colors: ["#22c55e", "#84cc16", "#eab308", "#f97316", "#ef4444"],
      labels: ["1: Very Low", "2: Low", "3: Moderate", "4: High", "5: Critical"]
    },
    description: "5-class dynamic landslide hazard rating derived for scenario analysis.",
    errorMessage: "Dynamic hazard class layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "dem_elevation",
    displayName: "Copernicus DEM Elevation (30m)",
    category: "raster",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "Copernicus GLO-30 DEM (4 Mosaicked Tiles)",
    units: "Meters ASL",
    tileOrSourceUrl: "/api/v1/tiles/elevation/{z}/{x}/{y}.png",
    defaultVisibility: false,
    opacity: 0.75,
    legend: {
      type: "gradient",
      color: "#facc15",
      colors: ["#1e293b", "#0284c7", "#eab308", "#ef4444", "#f8fafc"],
      labels: ["200m", "1500m", "3000m", "4500m", "6500m+"]
    },
    description: "30m Cloud-Optimized GeoTIFF raster derived from 4 Copernicus GLO-30 tiles.",
    errorMessage: "Elevation raster service unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "slope",
    displayName: "Terrain Slope (Degrees)",
    category: "raster",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "Copernicus GLO-30 Terrain Derivative",
    units: "Degrees (°)",
    tileOrSourceUrl: "/api/v1/tiles/slope/{z}/{x}/{y}.png",
    defaultVisibility: false,
    opacity: 0.75,
    legend: {
      type: "gradient",
      color: "#f97316",
      colors: ["#22c55e", "#eab308", "#f97316", "#ef4444"],
      labels: ["0° (Flat)", "15° (Moderate)", "35° (Steep)", "50°+ (Extreme)"]
    },
    description: "Slope angle in degrees computed using 3x3 Horn algorithm in EPSG:32643.",
    errorMessage: "Slope derivative raster service unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "aspect",
    displayName: "Terrain Aspect",
    category: "raster",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "Copernicus GLO-30 Aspect Derivative",
    units: "Degrees (° Azimuth)",
    tileOrSourceUrl: "/api/v1/tiles/aspect/{z}/{x}/{y}.png",
    defaultVisibility: false,
    opacity: 0.7,
    legend: {
      type: "gradient",
      color: "#a855f7",
      colors: ["#ef4444", "#eab308", "#22c55e", "#06b6d4", "#ef4444"],
      labels: ["N (0°)", "E (90°)", "S (180°)", "W (270°)", "N (360°)"]
    },
    description: "Slope orientation azimuth angle (0° - 360°) in EPSG:32643.",
    errorMessage: "Aspect derivative raster service unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "hillshade",
    displayName: "Copernicus Hillshade",
    category: "raster",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "Copernicus GLO-30 Hillshade Derivative",
    units: "8-bit Shading (0-255)",
    tileOrSourceUrl: "/api/v1/tiles/hillshade/{z}/{x}/{y}.png",
    defaultVisibility: true,
    opacity: 0.6,
    legend: {
      type: "gradient",
      color: "#94a3b8",
      colors: ["#000000", "#ffffff"],
      labels: ["Shadow (0)", "Illuminated (255)"]
    },
    description: "Analytical hillshade calculated with 315° azimuth and 45° altitude.",
    errorMessage: "Hillshade raster service unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "landslide_points",
    displayName: "NGDR Landslide Inventory Points",
    category: "hazard",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "GSI NGDR National Landslide Inventory",
    units: "2,370 Points",
    tileOrSourceUrl: "/api/v1/static-layers/landslides_points",
    defaultVisibility: true,
    opacity: 0.85,
    legend: {
      type: "circle",
      color: "#ef4444"
    },
    description: "2,370 verified historical landslide event points across J&K UT.",
    errorMessage: "Landslide points vector layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "landslide_polygons",
    displayName: "NGDR Landslide Polygons",
    category: "hazard",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "GSI NGDR Landslide Scar Polygons",
    units: "7,436 Polygons",
    tileOrSourceUrl: "/api/v1/static-layers/landslides_polygons",
    defaultVisibility: true,
    opacity: 0.5,
    legend: {
      type: "fill",
      color: "#dc2626"
    },
    description: "7,436 mapped landslide scar and deposit polygons across J&K UT.",
    errorMessage: "Landslide polygons vector layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "faults",
    displayName: "Tectonic Fault Lines",
    category: "geology",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "Geological Survey of India (NGDR)",
    units: "Line Features",
    tileOrSourceUrl: "/api/v1/static-layers/faults",
    defaultVisibility: true,
    opacity: 0.8,
    legend: {
      type: "line",
      color: "#ec4899"
    },
    description: "Active structural fault traces mapped across the Himalayan collision zone.",
    errorMessage: "Fault lines vector layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "thrusts",
    displayName: "Tectonic Thrust Lines",
    category: "geology",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "Geological Survey of India (NGDR)",
    units: "Line Features",
    tileOrSourceUrl: "/api/v1/static-layers/thrusts",
    defaultVisibility: true,
    opacity: 0.8,
    legend: {
      type: "line",
      color: "#a855f7"
    },
    description: "Major regional thrust faults (MBT, MCT, Zanskar Thrust).",
    errorMessage: "Thrust lines vector layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "lineaments",
    displayName: "Structural Lineaments",
    category: "geology",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "GSI Structural Lineament Mapping",
    units: "Line Features",
    tileOrSourceUrl: "/api/v1/static-layers/lineaments",
    defaultVisibility: true,
    opacity: 0.7,
    legend: {
      type: "line",
      color: "#c084fc"
    },
    description: "Geological lineament fractures and structural weakness zones.",
    errorMessage: "Lineaments vector layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "lithology",
    displayName: "Lithology (1:50k)",
    category: "geology",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "Geological Survey of India (GSI 1:50k)",
    units: "Rock Units",
    tileOrSourceUrl: "/api/v1/static-layers/lithology",
    defaultVisibility: false,
    opacity: 0.5,
    legend: {
      type: "fill",
      color: "#64748b"
    },
    description: "Rock types and surface lithological formations across J&K UT.",
    errorMessage: "Lithology vector layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "nh44",
    displayName: "NH-44 Highway Corridor",
    category: "infrastructure",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "National Highways Authority of India (NHAI)",
    units: "Corridor Geometry",
    tileOrSourceUrl: "/api/v1/static-layers/nh44",
    defaultVisibility: true,
    opacity: 0.9,
    legend: {
      type: "line",
      color: "#eab308"
    },
    description: "Critical Jammu-Srinagar NH-44 highway transport corridor.",
    errorMessage: "NH-44 vector layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "major_roads",
    displayName: "Major Roads Network",
    category: "infrastructure",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "OpenStreetMap / PWD Road Inventory",
    units: "Line Features",
    tileOrSourceUrl: "/api/v1/static-layers/major_roads",
    defaultVisibility: false,
    opacity: 0.7,
    legend: {
      type: "line",
      color: "#f59e0b"
    },
    description: "Primary and secondary road network connecting all 20 district headquarters.",
    errorMessage: "Road network vector layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "settlements",
    displayName: "Settlement Areas",
    category: "infrastructure",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "Census of India / Settlement Boundaries",
    units: "Point/Polygon Features",
    tileOrSourceUrl: "/api/v1/static-layers/settlements",
    defaultVisibility: false,
    opacity: 0.6,
    legend: {
      type: "circle",
      color: "#38bdf8"
    },
    description: "Human settlement points and urban build-up centers across J&K.",
    errorMessage: "Settlements vector layer unavailable.",
    dataVersion: "v1.0.0"
  },
  {
    id: "health_facilities",
    displayName: "Hospitals & Healthcare Facilities",
    category: "infrastructure",
    availability: "Available",
    processingPhase: "Phase 2",
    source: "Department of Health J&K",
    units: "877 Facilities",
    tileOrSourceUrl: "/api/v1/static-layers/health_facilities",
    defaultVisibility: false,
    opacity: 0.8,
    legend: {
      type: "circle",
      color: "#10b981"
    },
    description: "877 hospitals, primary health centers, and emergency care facilities.",
    errorMessage: "Health facilities vector layer unavailable.",
    dataVersion: "v1.0.0"
  }
];

export function getLayerById(id: string): LayerRegistryEntry | undefined {
  return MASTER_LAYER_REGISTRY.find(layer => layer.id === id);
}

export function getLayersByCategory(category: LayerRegistryEntry['category']): LayerRegistryEntry[] {
  return MASTER_LAYER_REGISTRY.filter(layer => layer.category === category);
}
